version: '3.4'
services:
  namecheap-ddns:
    build: .
    container_name: namecheap_ddns_updater
    restart: unless-stopped
    env_file: .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 4.4.4.4
